server{
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    #React/Vite front calls /api/*, with fetch()
    #In Compose, "backend" is the name of the backend service, so we can use it as a hostname to reach the backend container.

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    #React router fallback: /login, /app/assets, /app/assests/1234, etc. should all serve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}