spring.application.name=support-desk-api
server.port=${PORT:8080}

spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/support_desk_db?authSource=admin
spring.data.mongodb.auto-index-creation=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=3600000
