spring.application.name=support-desk-api
<<<<<<< Updated upstream
=======
spring.data.mongodb.uri=mongodb://support_app_user:supportdesk@localhost:27017/support_desk_db?authSource=support_desk_db
>>>>>>> Stashed changes
